# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('href', models.CharField(blank=True, max_length=50, null=True)),
                ('fatherid', models.IntegerField()),
                ('fathername', models.CharField(blank=True, max_length=20, null=True)),
                ('pri', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
