# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysBasis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
